
### get all product types - for ids
GET http://localhost:3500/producttypes HTTP/1.1

content-type: application/json

### get all product families
GET http://localhost:3500/productfamilies HTTP/1.1

content-type: application/json

### get all products
GET http://localhost:3500/product HTTP/1.1

content-type: application/json


### create product
POST http://localhost:3500/product/create HTTP/1.1
content-type: application/json

{
    "name" : "donica"
    
}

### get product by id
GET http://localhost:3500/product/getbyid/63067249c6bf37cd3abee015 HTTP/1.1
content-type: application/json

### update product by id
PUT http://localhost:3500/product/update HTTP/1.1
content-type: application/json

{
    "id" : "62c16a3e23701b9182c35d1d",
    "name": "jodła królewska"
}


### delete product
DELETE http://localhost:3500/product/delete HTTP/1.1
content-type: application/json

{
    "id" : "62c16969812db0ac295ae69b"
}


